export default  {
    siteTitle: 'Intranet App',
    placeholder: 'Your content shall be here',
    home: 'Home',
    news: 'News',
    departments: 'Departments',
    toolbox: 'Toolbox',
    announcements: 'Announcements',
    sections: 'Sections',
    about: 'About',
    notFound: 'But this page doesn\'t exist. Chech address again :)',
    termsTitle: 'Terms and Conditions',
    search: 'search',
    filter: 'filter',
    terms1: 'Using this application you accept',
    terms2: 'terms and conditions of use',
};
