export default {
  siteTitle: 'Intranet App',
  placeholder: 'Tutaj powinna być zawartość komponentu',
  home: 'Strona główna',
  news: 'Wiadomości',
  departments: 'Departamenty',
  toolbox: 'Niezbędnik',
  announcements: 'Ogłoszenia',
  sections: 'Sekcje',
  about: 'O nas',
  notFound: 'Strona nie istnieje. Sprawdź ponownie adres :)',
  termsTitle: 'Definicje i zasady użytkowania',
  search: 'szukaj',
  filter: 'filtruj',
  terms1: 'Używając tej aplikacji zobowiązujesz się',
  terms2: 'przesetrzegać zasad i regulacji',
  error: 'ERROR 404',
};
